### ISSUE TITLE
增加检测层报错

### ISSUE THREAD

**Issue by 17freeman** [bubbliiiing/yolov8-pytorch#22]
泡泡哥您好，我想在您的代码的基础上增加检测层，针对小样本的。但是前后修改了三次后，都是在同一处地方报了错。
![image](https://github.com/bubbliiiing/yolov8-pytorch/assets/42693096/6f52fa1c-aafc-45b9-951d-c5420e3b2cfe)
最后输出的P2，P3,P4,P5的shape都对，但就是报了错。
torch.Size([1, 64, 160, 160])
torch.Size([1, 128, 80, 80])
torch.Size([1, 256, 40, 40])
torch.Size([1, 512, 20, 20])
Traceback (most recent call last):
  File "C:/Users/eagle/Desktop/out/new_jincheng/yolov8-pytorch-master (2)/yolov8-pytorch-master/new_sum.py", line 22, in <module>
    flops, params = profile(m.to(device), (dummy_input,), verbose=False)
  File "C:\Anaconda3\envs\tf1.4\lib\site-packages\thop\profile.py", line 212, in profile
    model(*inputs)
  File "C:\Anaconda3\envs\tf1.4\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\eagle\Desktop\out\new_jincheng\yolov8-pytorch-master (2)\yolov8-pytorch-master\nets\new_yolo.py", line 208, in forward
    x[i] = torch.cat((self.cv2[i](x[i]), self.cv3[i](x[i])), 1)
  File "C:\Anaconda3\envs\tf1.4\lib\site-packages\torch\nn\modules\module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "C:\Anaconda3\envs\tf1.4\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "C:\Anaconda3\envs\tf1.4\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\eagle\Desktop\out\new_jincheng\yolov8-pytorch-master (2)\yolov8-pytorch-master\nets\new_backbone.py", line 35, in forward
    return self.act(self.bn(self.conv(x)))
  File "C:\Anaconda3\envs\tf1.4\lib\site-packages\torch\nn\modules\module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "C:\Anaconda3\envs\tf1.4\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Anaconda3\envs\tf1.4\lib\site-packages\torch\nn\modules\conv.py", line 454, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 128, 3, 3], expected input[1, 64, 160, 160] to have 128 channels, but got 64 channels instead

**Comment by 17freeman** [comment]
报错的代码在nets/yolo.py
![image](https://github.com/bubbliiiing/yolov8-pytorch/assets/42693096/c6c2a752-fc51-4bda-bdd6-4d3831d7ce4c)

**Comment by 17freeman** [comment]
泡哥，解决了
![image](https://github.com/bubbliiiing/yolov8-pytorch/assets/42693096/7f231b0b-b4bc-4b5c-82d7-bb0f49164338)
在ch中添加2*base_channel

**Comment by bubbliiiing** [comment]
OK 牛逼

**Comment by OrdinaryQin** [comment]
> 泡哥，解决了 ![image](https://user-images.githubusercontent.com/42693096/241125455-7f231b0b-b4bc-4b5c-82d7-bb0f49164338.png) 在ch中添加2*base_channel

老哥，方便提供一份泡泡哥的yolov8项目，您添加检测层的代码吗？感谢。
