### ISSUE TITLE
报错提示

### ISSUE THREAD

**Issue by caixiongjiang** [bubbliiiing/yolov8-pytorch#27]
Traceback (most recent call last):
  File "train.py", line 547, in <module>
    fit_one_epoch(model_train, model, ema, yolo_loss, loss_history, eval_callback, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, fp16, scaler, save_period, save_dir, local_rank)
  File "/data/caixj/yolov8-pytorch-master/utils/utils_fit.py", line 35, in fit_one_epoch
    loss_value = yolo_loss(outputs, bboxes)
  File "/data/caixj/yolov8-pytorch-master/nets/yolo_training.py", line 463, in __call__
    anchor_points * stride_tensor, gt_labels, gt_bboxes, mask_gt
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/data/caixj/yolov8-pytorch-master/nets/yolo_training.py", line 123, in forward
    mask_pos, align_metric, overlaps = self.get_pos_mask(pd_scores, pd_bboxes, gt_labels, gt_bboxes, anc_points, mask_gt)
  File "/data/caixj/yolov8-pytorch-master/nets/yolo_training.py", line 160, in get_pos_mask
    align_metric, overlaps  = self.get_box_metrics(pd_scores, pd_bboxes, gt_labels, gt_bboxes)
  File "/data/caixj/yolov8-pytorch-master/nets/yolo_training.py", line 208, in get_box_metrics
    overlaps        = bbox_iou(gt_bboxes.unsqueeze(2), pd_bboxes.unsqueeze(1), xywh=False, CIoU=True).squeeze(3).clamp(0)
  File "/data/caixj/yolov8-pytorch-master/nets/yolo_training.py", line 282, in bbox_iou
    inter = (b1_x2.minimum(b2_x2) - b1_x1.maximum(b2_x1)).clamp(0) * \
AttributeError: 'Tensor' object has no attribute 'minimum'
这是什么问题，训练的时候遇到的

**Comment by chauncey-eng** [comment]
+1我也有这问题，改成torch.max，torch.min之后，
File "E:\PycharmProjects\yolov8-pytorch-master\nets\yolo_training.py", line 38, in select_candidates_in_gts
    return bbox_deltas.amin(3).gt_(eps)
AttributeError: 'Tensor' object has no attribute 'amin'
又出现了这个问题
