### ISSUE TITLE
搞了半天了，怎么回事

### ISSUE THREAD

**Issue by dstawj** [bubbliiiing/yolov8-pytorch#34]
D:\anaconda3\envs\py1\python.exe F:\core_code\yolov8-pytorch-master\get_map.py 
Load model.
initialize network with normal type
Traceback (most recent call last):
  File "F:\core_code\yolov8-pytorch-master\get_map.py", line 92, in <module>
    yolo = YOLO(confidence = confidence, nms_iou = nms_iou)
  File "F:\core_code\yolov8-pytorch-master\yolo.py", line 91, in __init__
    self.generate()
  File "F:\core_code\yolov8-pytorch-master\yolo.py", line 105, in generate
    self.net.load_state_dict(torch.load(self.model_path, map_location=device))
  File "D:\anaconda3\envs\py1\lib\site-packages\torch\nn\modules\module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for YoloBody:
	size mismatch for cv3.0.2.weight: copying a param with shape torch.Size([80, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).
	size mismatch for cv3.0.2.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for cv3.1.2.weight: copying a param with shape torch.Size([80, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).
	size mismatch for cv3.1.2.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for cv3.2.2.weight: copying a param with shape torch.Size([80, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).
	size mismatch for cv3.2.2.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([1]).

进程已结束，退出代码为 1

**Comment by dstawj** [comment]
已经解决了，务必修改成这样！
<img width="288" alt="image" src="https://github.com/bubbliiiing/yolov8-pytorch/assets/126164492/d6fc1add-af31-4b95-918b-542dfb178046">

**Comment by aluoxuanwan** [comment]
请问楼主大佬运行yolo.py的时候改成和你一样的了，但是
在运行predict.py的时候，产生报错

D:\env\anaconda\envs\chq_1\lib\site-packages\torch\nn\modules\module.py:836: **UserWarning**: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  if param.grad is not None:
logs/best_epoch_weights.pth model, and classes loaded.
Configurations:
----------------------------------------------------------------------
|                     keys |                                   values|
----------------------------------------------------------------------
|               model_path |              logs/best_epoch_weights.pth|
|             classes_path |               model_data/voc_classes.txt|
|              input_shape |                               [640, 640]|
|                      phi |                                        n|
|               confidence |                                      0.5|
|                  nms_iou |                                      0.3|
|          letterbox_image |                                     True|
|                     cuda |                                     True|
----------------------------------------------------------------------
Input image filename:img/street.jpg
**Traceback** (most recent call last):
  File "C:\Users\Y07\Desktop\yolov8-pytorch-master\predict.py", line 91, in <module>
    r_image = yolo.detect_image(image, crop = crop, count=count)
  File "C:\Users\Y07\Desktop\yolov8-pytorch-master\yolo.py", line 211, in detect_image
    label_size = draw.textsize(label, font)
AttributeError: 'ImageDraw' object has no attribute 'textsize'

**Comment by KeciaHH** [comment]
> 请问楼主大佬运行yolo.py的时候改成和你一样的了，但是 在运行predict.py的时候，产生报错
> 
> ## D:\env\anaconda\envs\chq_1\lib\site-packages\torch\nn\modules\module.py:836: **UserWarning**: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/[pytorch/pytorch/pull/30531](https://github.com/pytorch/pytorch/pull/30531) for more informations. (Triggered internally at C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
> if param.grad is not None:
> logs/best_epoch_weights.pth model, and classes loaded.
> Configurations:
> ## | keys | values|
> ## | model_path | logs/best_epoch_weights.pth|
> | classes_path | model_data/voc_classes.txt|
> | input_shape | [640, 640]|
> | phi | n|
> | confidence | 0.5|
> | nms_iou | 0.3|
> | letterbox_image | True|
> | cuda | True|
> Input image filename:img/street.jpg **Traceback** (most recent call last): File "C:\Users\Y07\Desktop\yolov8-pytorch-master\predict.py", line 91, in r_image = yolo.detect_image(image, crop = crop, count=count) File "C:\Users\Y07\Desktop\yolov8-pytorch-master\yolo.py", line 211, in detect_image label_size = draw.textsize(label, font) AttributeError: 'ImageDraw' object has no attribute 'textsize'

同问 请问解决了吗
