### ISSUE TITLE
CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemv(handle, op, m, n, &alpha, a, lda, x, incx, &beta, y, incy)`

### ISSUE THREAD

**Issue by feifeitu1** [bubbliiiing/yolov8-pytorch#40]
请问执行train.py的时候出现这个是什么原因啊，搞了好久都没搞好，数据集用的就是给的VOC数据集
类别数量： 20
initialize network with normal type
Load weights model_data/yolov8_s.pth.

Successful Load Key: ['backbone.stem.conv.weight', 'backbone.stem.bn.weight', 'backbone.stem.bn.bias', 'backbone.stem.bn.running_mean', 'backbone.stem.bn.running_var', 'backbone.stem.bn.num_batches_tracked', 'backbone.dark2.0.conv.weight', 'backbone.dark2.0.bn.weight', 'backbone.dark2.0.bn.bias', 'backbone.dark2.0.bn.running_mean', 'backbone.dark2.0.bn.running_var', 'backbone.dark2.0.bn.num_batches_tracked', 'backbone.dark2.1.cv1.conv.weight', 'backbone.dark2.1.cv1.bn.weight', 'backbone.dark2.1.cv1.bn.bias', 'backbo ……
Successful Load Key Num: 349

Fail To Load Key: ['cv3.0.2.weight', 'cv3.0.2.bias', 'cv3.1.2.weight', 'cv3.1.2.bias', 'cv3.2.2.weight', 'cv3.2.2.bias'] ……
Fail To Load Key num: 6

温馨提示，head部分没有载入是正常现象，Backbone部分没有载入是错误的。
Epoch 1/300:   0%|          | 0/544 [00:00<?, ?it/s<class 'dict'>]Configurations:
----------------------------------------------------------------------
|                     keys |                                   values|
----------------------------------------------------------------------
|             classes_path |               model_data/voc_classes.txt|
|               model_path |                  model_data/yolov8_s.pth|
|              input_shape |                               [640, 640]|
|               Init_Epoch |                                        0|
|             Freeze_Epoch |                                       50|
|           UnFreeze_Epoch |                                      300|
|        Freeze_batch_size |                                       32|
|      Unfreeze_batch_size |                                       16|
|             Freeze_Train |                                     True|
|                  Init_lr |                                     0.01|
|                   Min_lr |                                   0.0001|
|           optimizer_type |                                      sgd|
|                 momentum |                                    0.937|
|            lr_decay_type |                                      cos|
|              save_period |                                       10|
|                 save_dir |                                     logs|
|              num_workers |                                        4|
|                num_train |                                    17416|
|                  num_val |                                     1936|
----------------------------------------------------------------------
Start Train
Traceback (most recent call last):
  File "C:/Users/25588/Desktop/yolov8/train.py", line 560, in <module>
    fit_one_epoch(model_train, model, ema, yolo_loss, loss_history, eval_callback, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, fp16, scaler, save_period, save_dir, local_rank)
  File "C:\Users\25588\Desktop\yolov8\utils\utils_fit.py", line 35, in fit_one_epoch
    loss_value = yolo_loss(outputs, bboxes)
  File "C:\Users\25588\Desktop\yolov8\nets\yolo_training.py", line 466, in __call__
    pred_bboxes = self.bbox_decode(anchor_points, pred_distri)  # xyxy, (b, h*w, 4)
  File "C:\Users\25588\Desktop\yolov8\nets\yolo_training.py", line 419, in bbox_decode
    pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemv(handle, op, m, n, &alpha, a, lda, x, incx, &beta, y, incy)`
Epoch 1/300:   0%|          | 0/544 [00:31<?, ?it/s<class 'dict'>]

Process finished with exit code 1

**Comment by JRStudio-107** [comment]
试着在终端输入unset LD_LIBRARY_PATH

**Comment by nabiroro** [comment]
'unset' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by nabiroro** [comment]
> 试着在终端输入unset LD_LIBRARY_PATH

'unset' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by nabiroro** [comment]
请问解决了吗

**Comment by wall633** [comment]
解决了吗
