### ISSUE TITLE
yolo系列全部有问题，训练解码结果不对

### ISSUE THREAD

**Issue by williamlzw** [bubbliiiing/yolov8-pytorch#6]
yolo系列全部有问题，不加载预训练模型，解码结果偏差很大

**Comment by bubbliiiing** [comment]
……你训练了吗？数据集很大吗？

**Comment by williamlzw** [comment]
有qq群，微信群吗

**Comment by bubbliiiing** [comment]
……你看注释了？

**Comment by williamlzw** [comment]
Freeze_Train        = False，不进行冻结训练，我移植模型和解码到torchsharp，训练效果也不好。

**Comment by bubbliiiing** [comment]
……说了啊，没有预训练权重需要注意什么

**Comment by Milkyway-xX** [comment]
你确定就这几十张图能训练？

**Comment by bubbliiiing** [comment]
有预训练可以勉强用用

**Comment by dstawj** [comment]
D:\anaconda3\envs\py1\python.exe F:\core_code\yolov8-pytorch-master\get_map.py 
Load model.
initialize network with normal type
Traceback (most recent call last):
  File "F:\core_code\yolov8-pytorch-master\get_map.py", line 92, in <module>
    yolo = YOLO(confidence = confidence, nms_iou = nms_iou)
  File "F:\core_code\yolov8-pytorch-master\yolo.py", line 91, in __init__
    self.generate()
  File "F:\core_code\yolov8-pytorch-master\yolo.py", line 105, in generate
    self.net.load_state_dict(torch.load(self.model_path, map_location=device))
  File "D:\anaconda3\envs\py1\lib\site-packages\torch\nn\modules\module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for YoloBody:
	size mismatch for cv3.0.2.weight: copying a param with shape torch.Size([80, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).
	size mismatch for cv3.0.2.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for cv3.1.2.weight: copying a param with shape torch.Size([80, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).
	size mismatch for cv3.1.2.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for cv3.2.2.weight: copying a param with shape torch.Size([80, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).
	size mismatch for cv3.2.2.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([1]).

进程已结束，退出代码为 1
