### ISSUE TITLE
TypeError: 'bool' object is not callable (Sometimes range instead of bool)

### ISSUE THREAD

**Issue by Nikhil-Rao20** [bubbliiiing/yolov8-pytorch#69]
I followed the exact instructions given and I am experimenting with the PASCAL VOC [2007](https://www.kaggle.com/datasets/zaraks/pascal-voc-2007) and [2012](https://www.kaggle.com/datasets/gopalbhattrai/pascal-voc-2012-dataset). And I have getting an error which says:
```
initialize network with normal type
Configurations:
----------------------------------------------------------------------
|                     keys |                                   values|
----------------------------------------------------------------------
|             classes_path |                 /content/voc_classes.txt|
|               model_path |                                         |
|              input_shape |                               [640, 640]|
|               Init_Epoch |                                        0|
|             Freeze_Epoch |                                       50|
|           UnFreeze_Epoch |                                      200|
|        Freeze_batch_size |                                       32|
|      Unfreeze_batch_size |                                       16|
|             Freeze_Train |                                    False|
|                  Init_lr |                                     0.01|
|                   Min_lr |                                   0.0001|
|           optimizer_type |                                      sgd|
|                 momentum |                                    0.937|
|            lr_decay_type |                                      cos|
|              save_period |                                       10|
|                 save_dir |                                     logs|
|              num_workers |                                        4|
|                num_train |                                    13870|
|                  num_val |                                     1542|
----------------------------------------------------------------------
Start Train
Epoch 1/200:   0%|          | 0/866 [00:00<?, ?it/s<class 'dict'>]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-68-398137c9d274>](https://localhost:8080/#) in <cell line: 17>()
    537 
    538             set_optimizer_lr(optimizer, lr_scheduler_func, epoch)
--> 539             fit_one_epoch(model_train, model, ema, yolo_loss, loss_history, eval_callback, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, fp16, scaler, save_period, save_dir, local_rank)
    540 
    541             if distributed:

4 frames
[<ipython-input-59-f91bb3236039>](https://localhost:8080/#) in fit_one_epoch(model_train, model, ema, yolo_loss, loss_history, eval_callback, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, Epoch, cuda, fp16, scaler, save_period, save_dir, local_rank)
     13         pbar = tqdm(total=epoch_step,desc=f'Epoch {epoch + 1}/{Epoch}',postfix=dict,mininterval=0.3)
     14     model_train.train()
---> 15     for iteration, batch in enumerate(gen):
     16         if iteration >= epoch_step:
     17             break

[/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py](https://localhost:8080/#) in __next__(self)
    628                 # TODO(https://github.com/pytorch/pytorch/issues/76750)
    629                 self._reset()  # type: ignore[call-arg]
--> 630             data = self._next_data()
    631             self._num_yielded += 1
    632             if self._dataset_kind == _DatasetKind.Iterable and \

[/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py](https://localhost:8080/#) in _next_data(self)
   1342             else:
   1343                 del self._task_info[idx]
-> 1344                 return self._process_data(data)
   1345 
   1346     def _try_put_index(self):

[/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py](https://localhost:8080/#) in _process_data(self, data)
   1368         self._try_put_index()
   1369         if isinstance(data, ExceptionWrapper):
-> 1370             data.reraise()
   1371         return data
   1372 

[/usr/local/lib/python3.10/dist-packages/torch/_utils.py](https://localhost:8080/#) in reraise(self)
    704             # instantiate since we don't know how to
    705             raise RuntimeError(msg) from None
--> 706         raise exception
    707 
    708 

TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "<ipython-input-61-b6184597b9a6>", line 41, in __getitem__
    shuffle(lines)
TypeError: 'bool' object is not callable
```

Please help me solve this issue, I am unable to get where the actual problem is.
Thank you

**Comment by Nikhil-Rao20** [comment]
I solved this issue by not creating the lists in a comprehensive manner and using a traditional method.
