### ISSUE TITLE
ParseTensorData: Assertion `elem_cnt == (raw_data_size / sizeof(int64_t))` failed.

### ISSUE THREAD

**Issue by hhhhpaaa** [bubbliiiing/yolov8-pytorch#8]
how to slove this problem? I don't kown what happened.

Simplifying with onnx-simplifier 0.4.19.
Traceback (most recent call last):
  File "E:\Python.workspace\biyesheji\yolov8-pytorch-master\predict.py", line 173, in <module>
    yolo.convert_to_onnx(simplify, onnx_save_path)
  File "E:\Python.workspace\biyesheji\yolov8-pytorch-master\yolo.py", line 358, in convert_to_onnx
    model_onnx, check = onnxsim.simplify(
  File "C:\Users\c2793\.conda\envs\pytorch\lib\site-packages\onnxsim\onnx_simplifier.py", line 186, in simplify
    model_opt_bytes = C.simplify(
RuntimeError: D:\a\onnx-simplifier\onnx-simplifier\third_party\onnx-optimizer\onnxoptimizer\passes\tensor_util.cc:74: ParseTensorData: Assertion `elem_cnt == (raw_data_size / sizeof(int64_t))` failed.

**Comment by hhhhpaaa** [comment]
I successfully simplify onnx model. In Ubuntu, it works. It seems like something is wrong with Onnx-Simplifier in Windows.

**Comment by hhhhpaaa** [comment]
> I successfully simplify onnx model. In Ubuntu, it works. It seems like something is wrong with Onnx-Simplifier in Windows.

This issue is fixed in the 0.4.22 version.
